start
    = first:clean_expr rest:clean_expr* {return [first].concat(rest);}

clean_expr
    = ws* exp:expression ws* {return exp;}

expression
    = "(" list:clean_expr* ")" {return list;}
    / single:atom {return single;}
    / "'" q_expr:clean_expr {return ["qoute", q_expr];}

comment
    = ";;" [^\n\r]*

atom
    = chars:validchar+ { return chars.join(""); }

validchar
    = [0-9a-zA-Z_?!+\-=@#$%^&*/.]

ws
    = comment
    / [ \t\n\r\f\v]
